import React, { useState, useEffect } from 'react';
import { Droplet, Settings, Wrench, Activity, ArrowUpCircle, Navigation } from 'lucide-react';
import './ETPServices.css'; // Import the CSS file
import ETP from "../../assets/ETP-Services.jpg"
import { useNavigate } from 'react-router-dom';

const ETPServices=()=> {
  const [isVisible, setIsVisible] = useState(false);
         const navigate=useNavigate();
           useEffect(() => {
             setIsVisible(true);
           }, []);
          
           const handleBack=()=>{
            navigate("/service");
           }
         
         
           return (
             <div className="ro-container">

               {/* Hero Section with Animation */}
               <div className={`ro-hero ${isVisible ? 'visible' : ''}`}>
                 <div className="ro-hero-content">
                   <h1 className="ro-hero-title">ETP Services</h1>
                   <div className="ro-hero-image-container">
                     <img src={ETP} alt="Reverse Osmosis" className="ro-hero-image" />
                     <div className="ro-hero-overlay">
                       <p className="ro-hero-tagline">Pure Water. Better Life.</p>
                     </div>
                   </div>
                 </div>
               </div>
         
               {/* Main Content */}
               <div className="ro-main-container">
                 <div className={`ro-content-card ${isVisible ? 'visible' : ''}`}>
                   <div className="ro-section-header">
                     <Droplet className="ro-icon" size={28} />
                     <h2 className="ro-section-title">
                       We offer comprehensive ETP services for your purest water needs
                     </h2>
                   </div>
                   <p className="ro-intro-text">
                    We offers Effluent Treatment Plant (ETP) Services, they would likely specialize 
                    in treating industrial wastewater, or effluent, generated by manufacturing processes.
                    This treatment ensures that harmful chemicals and pollutants are removed before the 
                    water is discharged into the environment or reused in the industrial process. ETPs 
                    are essential for industries that produce high levels of wastewater containing hazardous 
                    chemicals, oils, heavy metals, and other contaminants.
                   </p>
         
                   {/* Service Section 1 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="ETP Design and Installation"
                     delay="delay-400"
                     isVisible={isVisible}
                     services={[
                       { title: "Industrial ETP Systems", content: "Designing and installing ETPs for industries such as textiles, pharmaceuticals, chemicals, food processing, and metal plating, where large volumes of effluent with varying levels of contamination are generated." },
                       { title: "Custom ETP Design", content: "Offering customized ETP systems based on the specific requirements of the industry, including the type of pollutants in the effluent, flow rates, and local discharge standards." },
                       { title: "Compact ETP Systems for SMEs", content: "Providing small- and medium-scale industries with compact ETP systems that are cost-effective and space-efficient, meeting their effluent treatment needs without high capital expenditure." }
                     ]}
                   />
         
                   {/* Service Section 2 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Types of ETP Technologies Offered"
                     delay="delay-500"
                     isVisible={isVisible}
                     services={[
                       { title: "Physico-Chemical Treatment", content: "Implementing ETPs with physical and chemical treatment processes such as coagulation, flocculation, and sedimentation to remove suspended solids, heavy metals, and toxic chemicals from industrial effluent." },
                       { title: " Biological Treatment", content: "Installing biological treatment systems like activated sludge processes, Moving Bed Biofilm Reactors (MBBR), or Sequential Batch Reactors (SBR) to biologically degrade organic contaminants in wastewater." },
                       { title: " Tertiary Treatment Systems", content: "Offering advanced treatment methods such as membrane filtration, reverse osmosis (RO), activated carbon filtration, or UV disinfection to produce high-quality treated water suitable for reuse or safe discharge." },
                       { title: "Sludge Treatment and Dewatering", content: "Providing sludge handling solutions, including sludge thickening, dewatering, and safe disposal of sludge generated during the effluent treatment process." },
  
     
                     ]}
                   />
         
                   {/* Service Section 3 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}  // ⬅️ Changed from <Tool ... />
                     title="ETP Operation and Maintenance Services"
                     delay="delay-600"
                     isVisible={isVisible}
                     services={[
                     { title: "Regular Maintenance Services", content: "Offering routine maintenance services for ETPs to ensure efficient operation, including cleaning clarifiers, inspecting pumps, and replacing damaged membranes or filters." },
                     { title: "Sludge Management and Disposal", content: "Managing and disposing of sludge generated in the ETP system in an environmentally friendly manner, ensuring compliance with waste disposal regulations." },
                     { title: "Chemical Dosing Management", content: "Monitoring and adjusting chemical dosing systems to ensure optimal performance in processes like pH neutralization, coagulation, or precipitation, depending on the contaminants in the effluent." },
                     { title: "ETP System Audits", content: "Conducting audits to assess the performance of the ETP, identifying any operational inefficiencies, and recommending improvements to enhance treatment efficacy." }
  
                  ]}
         />
         
                   {/* Service Section 4 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Water Quality Monitoring and Compliance"
                     delay="delay-700"
                     isVisible={isVisible}
                     services={[
                       { title: "Effluent Testing and Certification", content: "Regularly testing the treated effluent for key parameters such as Chemical Oxygen Demand (COD), Biological Oxygen Demand (BOD), Total Suspended Solids (TSS), and pH to ensure compliance with regulatory standards." },
                       { title: "Compliance with Environmental Regulations", content: "Ensuring that treated effluent meets local and national environmental discharge standards, helping industries avoid penalties and maintain sustainable operations." },
                       { title: "Real-Time Monitoring Systems", content: "Implementing automated monitoring systems that provide real-time data on effluent quality, flow rates, and operational parameters, ensuring continuous compliance and allowing for quick corrective actions." },
                    ]}
                   />
         
                   {/* Service Section 5 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="ETP Repairs and Upgrades"
                     delay="delay-800"
                     isVisible={isVisible}
                     services={[
                       { title: "Component Repair and Replacement", content: "Repairing or replacing faulty components in the ETP, such as pumps, aerators, diffusers, or membranes, to restore system performance and avoid production downtime." },
                       { title: "System Upgrades for Capacity Expansion", content: "Upgrading existing ETPs to handle increased effluent loads by adding new treatment units or upgrading components to meet growing industrial demands." },
                       { title: "Retrofit Solutions", content: "Offering retrofitting services to modernize old or inefficient ETPs with advanced treatment technologies like MBR or ultrafiltration, improving treatment efficiency and water quality." },
                       { title: "Energy-Efficient Upgrades", content: "Implementing energy-efficient technologies like low-energy blowers, high-efficiency pumps, or biogas recovery systems to reduce the operational costs of ETPs." }

        
                     ]}
                   />
         
                   {/* Service Section 6 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Effluent Recycling and Reuse Solutions"
                     delay="delay-900"
                     isVisible={isVisible}
                     services={[
                       { title: "Water Reuse in Industrial Processes", content: "Installing advanced treatment units such as reverse osmosis or ultrafiltration systems to treat effluent to a quality suitable for reuse in industrial processes like cooling, boiler feed, or cleaning." },
                       { title: "Zero Liquid Discharge (ZLD) Systems", content: "Offering ZLD solutions that treat and recycle all wastewater, recovering water for reuse and ensuring that no effluent is discharged into the environment, which is ideal for industries in water-scarce areas or with strict discharge regulations." },
                       { title: "Closed-Loop Water Systems", content: "Designing closed-loop systems that allow industries to recycle treated effluent multiple times, reducing freshwater consumption and minimizing wastewater generation." }
        
                     ]}
                   />
        
                   {/* Service Section 7 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Sustainable and Eco-Friendly ETP Solutions"
                     delay="delay-900"
                     isVisible={isVisible}
                     services={[
                       { title: "Green Chemistry Solutions", content: "Offering eco-friendly treatment chemicals and processes that minimize the use of hazardous substances in effluent treatment, supporting industries in their sustainability efforts." },
                       { title: "Energy-Efficient Treatment Processes", content: "Implementing low-energy treatment solutions like anaerobic digestion, which produces biogas as a by-product, or natural treatment systems like constructed wetlands, reducing the carbon footprint of effluent treatment." },
                       { title: "Water and Energy Conservation Plans", content: "Designing ETPs that optimize water and energy use, promoting resource efficiency and helping industries achieve their sustainability goals." },
   
        
                     ]}
                   />
        
                    {/* Service Section 8 */}
                    <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Consultation and Customization Services"
                     delay="delay-900"
                     isVisible={isVisible}
                     services={[
                       { title: "Effluent Analysis and System Design", content: "Providing detailed effluent analysis and designing customized treatment systems based on the nature of the wastewater, industry-specific needs, and discharge regulations." },
                       { title: "Turnkey ETP Solutions", content: "Offering end-to-end ETP project services, including system design, procurement, installation, commissioning, and training, ensuring hassle-free implementation for industrial clients." },
                       { title: "Cost-Benefit Analysis and Feasibility Studies", content: "Conducting feasibility studies and cost analyses to help industries choose the most suitable effluent treatment solution based on their budget and operational requirements." },
        
                     ]}
                   />
        
                   {/* Service Section 9 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Training and Support Services"
                     delay="delay-900"
                     isVisible={isVisible}
                     services={[
                       { title: "Operator Training", content: "Offering training programs for ETP operators to ensure proper operation, maintenance, and troubleshooting of the treatment plant, ensuring efficient and compliant wastewater management." },
                       { title: "24/7 Technical Support", content: "Providing continuous technical support to address operational issues, optimize system performance, and ensure compliance with changing environmental regulations." },
        
                     ]}
                   />
        
                   {/* Service Section 10 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Benefits of ETP Services"
                     delay="delay-900"
                     isVisible={isVisible}
                     services={[
                       { title: "Environmental Compliance", content: " Ensures that industrial wastewater is treated to meet local environmental regulations, protecting water bodies and avoiding fines or penalties." },
                       { title: "Water Conservation", content: "Treated effluent can be reused in industrial processes, reducing the demand for freshwater and lowering water costs for industries." },
                       { title: "Reduced Environmental Impact", content: "By properly treating and managing effluent, industries can reduce their environmental footprint and promote sustainable practices." },
                       { title: "Improved Efficiency", content: "Regular maintenance and optimization of ETP systems ensure continuous, efficient operation, reducing downtime and operating costs." },
                       { title: "Custom Solutions", content: "Durga Traders can offer tailored ETP solutions to meet the specific needs of different industries, ensuring the best possible treatment outcome." }

        
                     ]}
                   />
                   {/* Service Section 11 */}
                   <ServiceSection 
                     icon={<Navigation className="ro-icon" size={24} />}
                     title="Applications of ETP Services"
                     delay="delay-900"
                     isVisible={isVisible}
                     services={[
                       { title: "Textile and Dyeing Industry", content: "Treating effluents containing dyes, chemicals, and heavy metals to prevent environmental contamination and meet discharge standards." },
                       { title: "Pharmaceutical and Chemical Manufacturing", content: "Ensuring the safe treatment of effluents containing toxic chemicals, organic pollutants, and heavy metals before discharge or reuse." },
                       { title: "Food and Beverage Industry", content: "Managing high levels of organic waste, fats, oils, and grease in effluents, ensuring compliance with environmental norms and promoting water reuse." },
                       { title: "Automobile and Metal Plating Industries", content: "Treating effluents containing oils, greases, heavy metals, and suspended solids before discharge or recycling the water for industrial processes." },,
                       { title: "Pulp and Paper Industry", content: "Managing effluents rich in organic material, suspended solids, and chemicals to ensure environmentally responsible disposal or reuse." },

        
                     ]}
                   />
                 </div>
                 </div>
                 </div>
           );
        };
        const ServiceSection = ({ icon, title, delay, isVisible, services }) => {
            const [hovered, setHovered] = useState(null);
          
            return (
              <div className={`ro-service-section ${delay} ${isVisible ? 'visible' : ''}`}>
                <div className="ro-service-header">
                  {icon}
                  <h3 className="ro-service-title">{title}</h3>
                </div>
                <div className="ro-service-content">
                  {services.map((service, index) => (
                    <div 
                      key={index}
                      className={`ro-service-item ${hovered === index ? 'hovered' : ''}`}
                      onMouseEnter={() => setHovered(index)}
                      onMouseLeave={() => setHovered(null)}
                    >
                      <div className="ro-service-item-content">
                        <Droplet size={18} className="ro-service-item-icon" />
                        <div>
                          <span className="ro-service-item-title">{service.title}</span>
                          <span className="ro-service-item-description">{service.content}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          };
export default ETPServices;